### ISSUE TITLE
Standards for Open Data Release

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/open-data#1]
How to make data open?

What are the criterion?

What kinds of specification?

Contact information Template

Data Dictionary Template for Data Set

etc.

**Comment by tuliplab** [comment]
@ZiweiHou 

any progress along this line?

**Comment by ZiweiHou** [comment]
Instruction and example might help for this,
https://github.com/alangrafu/github-open-data-portal/wiki/How-to-publish-Open-Data-using-github
https://github.com/OpenExoplanetCatalogue/open_exoplanet_catalogue

**Comment by tuliplab** [comment]
@ZiweiHou 

This is just what we are doing.

But the key issue is : how to describe the data, any common standard in data description? 

Any information for point of content, or data set dictionary..... or any example.

You can check NJU Zhi-Hua Zhou's lamda group to see how they release their data set.

**Comment by ZiweiHou** [comment]
### **About the Macau** 

**About the Dataset**
This package contains text data for machine learning which has been used in (Paper name). It describes the data of tourists in Macau from January 2012 to April 2018.
References 

**ATTN:**   You can feel free to use the package (for academic purpose only) at your own risk. An acknowledge or citation to the above paper is required. For other purposes, please contact A/Prof. Gang Li (gangli@tulip.org.au).
### **Data Structure**
There are 258 features in total. The following table shows all features in Macau Dataset.


No. | Feature Name | Description | Data Type | No. | Feature Name | Description | Data Type
-- | -- | -- | -- | -- | -- | -- | --
1 | Date | non-null | object | 130 | best hotel macau | non-null | int64
2 | Arrival | non-null | int64 | 131 | sands casino | non-null | int64
3 | Hong Kong casino | non-null | int64 | 132 | halal food in macau | non-null | int64
4 | Shows in Macau | non-null | int64 | 133 | macau show bar | non-null | int64
5 | Singapore to Macau | non-null | int64 | 134 | lisboa casino | non-null | int64
6 | Macau Airlines | non-null | int64 | 135 | hotel lisboa macau | non-null | int64
7 | Macau on map | non-null | int64 | 136 | singapore | non-null | int64
8 | Tiger Airways | non-null | int64 | 137 | from hong kong to macau | non-null | int64
9 | Cathay Pacific | non-null | int64 | 138 | venetian casino macau | non-null | int64
10 | Show in Macau | non-null | int64 | 139 | shopping in hong kong | non-null | int64
11 | Macau Venetian | non-null | int64 | 140 | venetian macau casino | non-null | int64
12 | Galaxy Macau Hotel | non-null | int64 | 141 | shopping in macau | non-null | int64
13 | Macau grand hotel | non-null | int64 | 142 | macau food festival 2014 | non-null | int64
14 | Macau Tauranga | non-null | int64 | 143 | singapore airlines | non-null | int64
15 | casino in Macau | non-null | int64 | 144 | hong kong tourism | non-null | int64
16 | mgm macau | non-null | int64 | 145 | venetian macau | non-null | int64
17 | macau ferry terminal | non-null | int64 | 146 | macau shopping mall | non-null | int64
18 | macau restaurant jamaica | non-null | int64 | 147 | macau shopping guide | non-null | int64
19 | macao | non-null | int64 | 148 | ferry macau to hong kong airport | non-null | int64
20 | map of hong kong | non-null | int64 | 149 | hk to macau | non-null | int64
21 | macau food festival | non-null | int64 | 150 | macau food guide | non-null | int64
22 | cheap flights | non-null | int64 | 151 | hong kong weather | non-null | int64
23 | hong kong to macau travel time | non-null | int64 | 152 | casino lisboa macau | non-null | int64
24 | venetian hotel macau | non-null | int64 | 153 | world map | non-null | int64
25 | macau nightlife | non-null | int64 | 154 | hong kong to macau ferry | non-null | int64
26 | royal hotel | non-null | int64 | 155 | macau hotels | non-null | int64
27 | macau ferry schedule | non-null | int64 | 156 | macau food festival 2017 | non-null | int64
28 | cebu pacific | non-null | int64 | 157 | air macau | non-null | int64
29 | jetstar | non-null | int64 | 158 | macau things to do | non-null | int64
30 | thailand | non-null | int64 | 159 | google flights | non-null | int64
31 | flights to hong kong | non-null | int64 | 160 | hotel lisboa | non-null | int64
32 | macau food | non-null | int64 | 161 | macau china | non-null | int64
33 | macau hotel venetian | non-null | int64 | 162 | google map | non-null | int64
34 | hotel in macau | non-null | int64 | 163 | what to do in macau | non-null | int64
35 | flights to macau | non-null | int64 | 164 | wing on travel macau | non-null | int64
36 | hong kong macau ferry | non-null | int64 | 165 | macau food festival 2012 | non-null | int64
37 | weather in macau | non-null | int64 | 166 | weather in hong kong | non-null | int64
38 | macau restaurant menu | non-null | int64 | 167 | galaxy casino | non-null | int64
39 | macau weather | non-null | int64 | 168 | hongkong tourism | non-null | int64
40 | wing on travel | non-null | int64 | 169 | hong kong to macau | non-null | int64
41 | china map | non-null | int64 | 170 | wynn casino | non-null | int64
42 | macaulay culkin | non-null | int64 | 171 | macao restaurant | non-null | int64
43 | taboo show macau | non-null | int64 | 172 | macau city | non-null | int64
44 | dancing water show macau schedule | non-null | int64 | 173 | macau light show | non-null | int64
45 | best food in macau | non-null | int64 | 174 | map of macau | non-null | int64
46 | hotel macau | non-null | int64 | 175 | macau weather december | non-null | int64
47 | agoda | non-null | int64 | 176 | house of dancing water | non-null | int64
48 | macau hotel | non-null | int64 | 177 | macau airport | non-null | int64
49 | hongkong | non-null | int64 | 178 | hongkong macau ferry | non-null | int64
50 | asia travel | non-null | int64 | 179 | macau restaurant tauranga | non-null | int64
51 | city of dreams macau | non-null | int64 | 180 | ferry to macau | non-null | int64
52 | hong kong airport to macau | non-null | int64 | 181 | macau hk ferry | non-null | int64
53 | hong kong airport to macau ferry | non-null | int64 | 182 | travel agency | non-null | int64
54 | dancing water macau | non-null | int64 | 183 | wynn macau | non-null | int64
55 | macau magic show | non-null | int64 | 184 | macau food festival 2016 | non-null | int64
56 | china | non-null | int64 | 185 | macau casino | non-null | int64
57 | weather hong kong | non-null | int64 | 186 | macau island | non-null | int64
58 | macau portuguese restaurant | non-null | int64 | 187 | restaurants in macau | non-null | int64
59 | best food in hong kong | non-null | int64 | 188 | macau ferry | non-null | int64
60 | macau china weather | non-null | int64 | 189 | ferry macau hong kong | non-null | int64
61 | macau gaming lounge & bar | non-null | int64 | 190 | macau ferry terminal hong kong | non-null | int64
62 | galaxy macau | non-null | int64 | 191 | hongkong map | non-null | int64
63 | hong kong ferry to macau | non-null | int64 | 192 | macau ferry from hong kong | non-null | int64
64 | ferry terminal | non-null | int64 | 193 | macau ferry terminal map | non-null | int64
65 | hong kong light show | non-null | int64 | 194 | ozone bar hong kong | non-null | int64
66 | travel to macau | non-null | int64 | 195 | galaxy hotel | non-null | int64
67 | macau chinese restaurant | non-null | int64 | 196 | iifa awards 2013 macau full show | non-null | int64
68 | hk to macau ferry | non-null | int64 | 197 | macau galaxy | non-null | int64
69 | casinos macau | non-null | int64 | 198 | macau map | non-null | int64
70 | macau tourism | non-null | int64 | 199 | hotel in hong kong | non-null | int64
71 | macau shows | non-null | int64 | 200 | weather forecast hong kong | non-null | int64
72 | indian restaurant in macau | non-null | int64 | 201 | macau world map | non-null | int64
73 | hong kong macau | non-null | int64 | 202 | venetian casino | non-null | int64
74 | bangkok | non-null | int64 | 203 | airasia | non-null | int64
75 | super show 4 macau | non-null | int64 | 204 | macau package | non-null | int64
76 | hong kong airport | non-null | int64 | 205 | hong kong map | non-null | int64
77 | restaurant in macau | non-null | int64 | 206 | grand macau casino | non-null | int64
78 | macau food festival 2015 | non-null | int64 | 207 | hong kong ferry terminal | non-null | int64
79 | macau restaurants | non-null | int64 | 208 | macau tower | non-null | int64
80 | best restaurant in macau | non-null | int64 | 209 | bali | non-null | int64
81 | macau water show | non-null | int64 | 210 | macau hong kong | non-null | int64
82 | china travel | non-null | int64 | 211 | macao casino | non-null | int64
83 | macau travel guide | non-null | int64 | 212 | food festival macau | non-null | int64
84 | galaxy casino macau | non-null | int64 | 213 | skyscanner | non-null | int64
85 | openrice | non-null | int64 | 214 | AGODA | non-null | int64
86 | hong kong shopping | non-null | int64 | 215 | macaulay culkin.1 | non-null | int64
87 | hongkong weather | non-null | int64 | 216 | Skyscanner | non-null | int64
88 | good food in macau | non-null | int64 | 217 | 中国地图 | non-null | int64
89 | hong kong hotel | non-null | int64 | 218 | 亚洲旅行 | non-null | int64
90 | macau restaurant hong kong | non-null | int64 | 219 | 亚洲航空 | non-null | int64
91 | hongkong macau | non-null | int64 | 220 | 亚航 | non-null | int64
92 | weather in macau in december | non-null | int64 | 221 | 国泰航空 | non-null | int64
93 | weather forecast | non-null | int64 | 222 | 威尼斯人酒店 | non-null | int64
94 | accommodation in macau | non-null | int64 | 223 | 威尼斯赌场 | non-null | int64
95 | cheap flights to macau | non-null | int64 | 224 | 巴里 | non-null | int64
96 | venetian macau shopping | non-null | int64 | 225 | 捷星航空 | non-null | int64
97 | agoda macau | non-null | int64 | 226 | 新加坡天气 | non-null | int64
98 | hong kong | non-null | int64 | 227 | 梦想之城 | non-null | int64
99 | macau currency | non-null | int64 | 228 | 泰国 | non-null | int64
100 | macau shopping festival | non-null | int64 | 229 | 澳门 | non-null | int64
101 | iifa awards 2013 full show | non-null | int64 | 230 | 澳门住宿 | non-null | int64
102 | hong kong weather forecast | non-null | int64 | 231 | 澳门住宿攻略 | non-null | int64
103 | venetian | non-null | int64 | 232 | 澳门地图 | non-null | int64
104 | heart bar macau | non-null | int64 | 233 | 澳门塔 | non-null | int64
105 | galaxy | non-null | int64 | 234 | 澳门天气 | non-null | int64
106 | weather forecast in macau | non-null | int64 | 235 | 澳门威尼斯人 | non-null | int64
107 | halal food in hong kong | non-null | int64 | 236 | 澳门币 | non-null | int64
108 | food in macau | non-null | int64 | 237 | 澳门旅游景点大全 | non-null | int64
109 | banyan tree macau | non-null | int64 | 238 | 澳门机场 | non-null | int64
110 | macau cheap flights | non-null | int64 | 239 | 澳门美食 | non-null | int64
111 | venetian hotel | non-null | int64 | 240 | 澳门美食地图 | non-null | int64
112 | macau food blog | non-null | int64 | 241 | 澳门美食节 | non-null | int64
113 | macau tourism board | non-null | int64 | 242 | 澳门航空 | non-null | int64
114 | hong kong travel | non-null | int64 | 243 | 澳门赌场 | non-null | int64
115 | flights to macau from singapore | non-null | int64 | 244 | 澳门酒店 | non-null | int64
116 | mgm | non-null | int64 | 245 | 澳门银河 | non-null | int64
117 | city of dreams | non-null | int64 | 246 | 米高梅 | non-null | int64
118 | macau tour package | non-null | int64 | 247 | 谷歌地图 | non-null | int64
119 | macau travel blog | non-null | int64 | 248 | 轮渡码头 | non-null | int64
120 | macau gaming show | non-null | int64 | 249 | 香港 | non-null | int64
121 | the house of dancing water | non-null | int64 | 250 | 香港到澳门 | non-null | int64
122 | weather hk | non-null | int64 | 251 | 香港地图 | non-null | int64
123 | hong kong disneyland | non-null | int64 | 252 | 香港天气 | non-null | int64
124 | hong kong macau map | non-null | int64 | 253 | 香港天气预报 | non-null | int64
125 | macau time | non-null | int64 | 254 | 香港旅游 | non-null | int64
126 | hong kong ferry | non-null | int64 | 255 | 香港机场 | non-null | int64
127 | air asia | non-null | int64 | 256 | 香港购物 | non-null | int64
128 | macau weather today | non-null | int64 | 257 | 香港赌场 | non-null | int64
129 | weather singapore | non-null | int64 | 258 | 香港酒店 | non-null | int64

### **Additional information**

Field | Value
-- | --
Title | Macau tourists’ information
Type | Dataset
Language | English   & Chinese (Simplified)
License |  
Data Status | active
Update Frequency | annually
Landing Page |  
Date Published |  
Date Updated |  
Contact Point |  
Temporal Coverage | Date
Geospatial Coverage | Web link
Jurisdiction | 2015-06-01
Data Portal | http://www.ga.gov.au/place-names/PlaceDetails.jsp?submit1=VIC30457
Publisher/Agency | Tulip

**Comment by tuliplab** [comment]
@xhan97 

You need to make it available first on your private repository, after all ready, I will push it here.

**Comment by xhan97** [comment]
done
